overrides:
  '@mbler/mcx-types': 0.0.4-rc.8
  '@mbler/mcx-server': 0.1.5-rc.0

minimumReleaseAgeExclude:
  - '@ojang/vanilla-lootdata@0.0.1-rc.5'
  - '@mbler/mcx-component@0.0.2 || 0.0.3-rc.0'
  - '@mbler/mcx-core@0.1.3-rc.16'
  - '@mbler/mcx-server@0.1.5-rc.0'
  - '@mbler/mcx-types@0.0.4-rc.8'
